const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getData:        ()        => ipcRenderer.invoke('get-data'),
  getConfig:      ()        => ipcRenderer.invoke('get-config'),
  saveMemo:       (memo)    => ipcRenderer.invoke('save-memo', memo),
  deleteMemo:     (id)      => ipcRenderer.invoke('delete-memo', id),
  toggleStarred:  (id)      => ipcRenderer.invoke('toggle-starred', id),
  openMemo:       (memo)    => ipcRenderer.invoke('open-memo', memo),
  newMemo:        ()        => ipcRenderer.invoke('new-memo'),
  newMemoInFolder: (id)     => ipcRenderer.invoke('new-memo-in-folder', id),
  closeMemo:      (id)      => ipcRenderer.invoke('close-memo', id),
  saveFolder:     (f)       => ipcRenderer.invoke('save-folder', f),
  deleteFolder:   (id)      => ipcRenderer.invoke('delete-folder', id),
  moveMemo:       (p)       => ipcRenderer.invoke('move-memo', p),
  togglePin:      (id)      => ipcRenderer.invoke('toggle-pin', id),
  importStf:      (dir)     => ipcRenderer.invoke('import-stf', dir),
  saveSchedule:   (s)       => ipcRenderer.invoke('save-schedule', s),
  deleteSchedule: (id)      => ipcRenderer.invoke('delete-schedule', id),
  captureScreen:  ()        => ipcRenderer.invoke('capture-screen'),
  openFolderDialog: ()      => ipcRenderer.invoke('open-folder-dialog'),
  systemShutdown: ()        => ipcRenderer.invoke('system-shutdown'),
  systemLock:     ()        => ipcRenderer.invoke('system-lock'),
  showSidebar:    ()        => ipcRenderer.invoke('show-sidebar'),
  hideSidebar:    ()        => ipcRenderer.invoke('hide-sidebar'),
  toggleSidebar:  ()        => ipcRenderer.invoke('toggle-sidebar'),
  colorPickStart: (target)  => ipcRenderer.invoke('colorpick-start', target || null),
  colorPickEnd:   ()        => ipcRenderer.invoke('colorpick-end'),
  colorPickClose: (hex)     => ipcRenderer.send('colorpick-close', hex),
  saveConfig:     (cfg)     => ipcRenderer.invoke('save-config', cfg),
  previewKTab:    (show)    => ipcRenderer.invoke('preview-ktab', show),
  memoIsOpen:     (id)      => ipcRenderer.invoke('memo-is-open', id),
  installUpdate:       ()   => ipcRenderer.invoke('install-update'),
  openSettingsWindow:        ()   => ipcRenderer.invoke('open-settings-window'),
  openSidebarSettingsWindow: ()   => ipcRenderer.invoke('open-sidebar-settings-window'),
  closeSelf:           ()   => ipcRenderer.invoke('close-settings-window'),
  restoreBackup:  ()        => ipcRenderer.invoke('restore-backup'),
  quitApp:        ()        => ipcRenderer.invoke('quit-app'),
  openUrl:        (url)     => ipcRenderer.invoke('open-url', url),
  openBackupFolder: ()      => ipcRenderer.invoke('open-backup-folder'),
  folderSetPassword:    (p)  => ipcRenderer.invoke('folder-set-password', p),
  folderVerifyPassword: (p)  => ipcRenderer.invoke('folder-verify-password', p),
  folderLock:           (id) => ipcRenderer.invoke('folder-lock', id),
  folderRemovePassword: (p)  => ipcRenderer.invoke('folder-remove-password', p),
  folderIsUnlocked:     (id) => ipcRenderer.invoke('folder-is-unlocked', id),
  folderSendRecovery:   (id) => ipcRenderer.invoke('folder-send-recovery', id),
  folderVerifyTempReset:(p)  => ipcRenderer.invoke('folder-verify-temp-reset', p),
  saveRecoverySettings: (p)  => ipcRenderer.invoke('save-recovery-settings', p),
  closeAllMemos:  ()        => ipcRenderer.invoke('close-all-memos'),
  showAllMemos:   ()        => ipcRenderer.invoke('show-all-memos'),
  setLoginItem:   (v)       => ipcRenderer.invoke('set-login-item', v),
  getLoginItem:   ()        => ipcRenderer.invoke('get-login-item'),
  backupData:     ()        => ipcRenderer.invoke('backup-data'),

  openTodoColorPick: (bg, text) => ipcRenderer.invoke('open-todo-colorpick', bg, text),
  todoColorPickApply: (bg, text) => ipcRenderer.send('todo-colorpick-apply', bg, text),
  todoColorPickClose: ()         => ipcRenderer.invoke('todo-colorpick-close'),

  previewTheme:  (name) => ipcRenderer.invoke('preview-theme', name),
  getWhatsNew:      ()     => ipcRenderer.invoke('get-whats-new'),
  closeWhatsNew:    ()     => ipcRenderer.invoke('close-whats-new'),
  resizeWhatsNew:   (w, h) => ipcRenderer.invoke('resize-whats-new', w, h),
  on:  (ch, fn) => ipcRenderer.on(ch, (_, ...args) => fn(...args)),
  off: (ch, fn) => ipcRenderer.off(ch, fn),
});
